package com.market.bean;

import java.util.ArrayList;

/**
 * Created by litienan on 2017/9/20.
 */

public class CarsNameList {
    private ArrayList<String> carsName;

    public ArrayList getListNames() {
        carsName = new ArrayList<>();
        carsName.add("奥迪");
        carsName.add("阿斯顿 马丁");
        carsName.add("阿尔法 罗密欧");
        carsName.add("ALPINA");
        carsName.add("ARCFOX");
        carsName.add("本田");
        carsName.add("奔驰");
        carsName.add("宝马");
        carsName.add("别克");
        carsName.add("宝骏");
        carsName.add("比亚迪");
        carsName.add("标致");
        carsName.add("保时捷");
        carsName.add("北京");
        carsName.add("奔腾");
        carsName.add("宝沃");
        carsName.add("北汽幻速");
        carsName.add("宾利");
        carsName.add("北汽绅宝");
        carsName.add("北汽制造");
        carsName.add("北汽新能源");
        carsName.add("比速");
        carsName.add("北汽威旺");
        carsName.add("布加迪");
        carsName.add("巴博斯");
        carsName.add("北汽道打");
        carsName.add("长安");
        carsName.add("长安欧尚");
        carsName.add("长城");
        carsName.add("昌河");
        carsName.add("长安轻型车");
        carsName.add("长安跨越");
        carsName.add("成功");
        carsName.add("长江EV");
        carsName.add("大众");
        carsName.add("东风风行");
        carsName.add("东风风神");
        carsName.add("东南");
        carsName.add("东风风光");
        carsName.add("DS");
        carsName.add("道奇");
        carsName.add("东风");
        carsName.add("东风小康");
        carsName.add("东风风度");
        carsName.add("丰田");
        carsName.add("福特");
        carsName.add("法拉利");
        carsName.add("福田");
        carsName.add("菲亚特");
        carsName.add("福迪");
        carsName.add("福汽启腾");
        carsName.add("飞驰商务车");
        carsName.add("Faraday Future");
        carsName.add("广汽传祺");
        carsName.add("观致");
        carsName.add("GMC");
        carsName.add("广汽吉奥");
        carsName.add("哈弗");
        carsName.add("海马");
        carsName.add("红旗");
        carsName.add("汉腾");
        carsName.add("华泰");
        carsName.add("黄海");
        carsName.add("哈飞");
        carsName.add("华颂");
        carsName.add("海格");
        carsName.add("汇众");
        carsName.add("恒天");
        carsName.add("华凯");
        carsName.add("吉利");
        carsName.add("JEEP");
        carsName.add("江淮");
        carsName.add("捷豹");
        carsName.add("江铃");
        carsName.add("金杯");
        carsName.add("九龙");
        carsName.add("金龙");
        carsName.add("金旅");
        carsName.add("吉威新能源");
        carsName.add("君马");
        carsName.add("凯迪拉克");
        carsName.add("凯翼");
        carsName.add("克莱斯勒");
        carsName.add("开瑞");
        carsName.add("科瑞斯的");
        carsName.add("卡升");
        carsName.add("科尼塞克");
        carsName.add("康迪全球鹰");
        carsName.add("卡威");
        carsName.add("KTM");
        carsName.add("雷克萨斯");
        carsName.add("路虎");
        carsName.add("铃木");
        carsName.add("林肯");
        carsName.add("猎豹");
        carsName.add("雷诺");
        carsName.add("陆风");
        carsName.add("兰博基尼");
        carsName.add("力帆");
        carsName.add("劳斯莱斯");
        carsName.add("领克");
        carsName.add("路特斯");
        carsName.add("蓝海房车");
        carsName.add("陆地方舟");
        carsName.add("理念");
        carsName.add("雷丁");
        carsName.add("罗伦士");
        carsName.add("马自达");
        carsName.add("名爵");
        carsName.add("玛莎拉蒂");
        carsName.add("MINI");
        carsName.add("迈凯轮");
        carsName.add("摩根");
        carsName.add("纳智捷");
        carsName.add("讴歌");
        carsName.add("帕加尼");
        carsName.add("起亚");
        carsName.add("奇瑞");
        carsName.add("启辰");
        carsName.add("庆铃");
        carsName.add("前途");
        carsName.add("奇点汽车");
        carsName.add("日产");
        carsName.add("荣威");
        carsName.add("斯科达");
        carsName.add("三菱");
        carsName.add("上汽大通");
        carsName.add("斯巴鲁");
        carsName.add("SWM斯威");
        carsName.add("Smart");
        carsName.add("双龙");
        carsName.add("山姆");
        carsName.add("赛麟");
        carsName.add("世爵");
        carsName.add("陕汽通家");
        carsName.add("特斯拉");
        carsName.add("泰卡特");
        carsName.add("腾势");
        carsName.add("沃尔沃");
        carsName.add("WEY");
        carsName.add("五菱");
        carsName.add("五十铃");
        carsName.add("蔚来");
        carsName.add("潍柴英致");
        carsName.add("威麟");
        carsName.add("威兹曼");
        carsName.add("潍柴欧睿");
        carsName.add("雪弗兰");
        carsName.add("现代");
        carsName.add("雪铁龙");
        carsName.add("星客特");
        carsName.add("新凯");
        carsName.add("星驰");
        carsName.add("英菲尼迪");
        carsName.add("一汽");
        carsName.add("驭胜");
        carsName.add("野马");
        carsName.add("依维柯");
        carsName.add("宇通");
        carsName.add("云度");
        carsName.add("众泰");
        carsName.add("中华");
        carsName.add("知豆");
        carsName.add("中欧房车");
        carsName.add("中兴");
        carsName.add("之诺");
        carsName.add("重汽王牌");

        return carsName;
    }


}
